### PR TITLE
Add example data

### PR DESCRIPTION
**Pull request by jpherdi**
Fix issue #365

### CODE REVIEW

**Comment by chrbeckm** [comment]
I think it is better to save the generated data in a file. This way, the participants can use `np.genfromtxt` again.

```python
rng = np.random.default_rng(seed=42)
x = rng.random(10)
y = 1.6 * x + 0.2 * rng.uniform(-1,1, len(x))
np.savetxt("daten.txt", np.column_stack([x, y]), header="x y")
```

**Comment by jpherdi** [comment]
@chrbeckm What do you mean by "same between implementation and and solution"?
I fixed the solution correspondingly.

**Comment by chrbeckm** [comment]
I overlooked the seed, so I am wrong, the values will be the same.

**Comment by jpherdi** [comment]
You like it better, this way?

**Review by chrbeckm — APPROVED** [review]

**Pull request merged**
