### PR TITLE
Update environment to use python 3.11 and conda-forge

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by aknierim** [comment]
Current versions of `notebook` (i.e. `>=7.0.0`) seem to be incompatible with extensions and throw
```
ModuleNotFoundError: No module named 'notebook.base'
```
when using `jupyter-nbconvert` thus failing the build. I guess for now we may want to consider using `notebook<7.0.0` in `environment.yml`.

**Comment by LuckyJosh** [comment]
It seems v7.0 made alot of changes:

At a glance 
https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

tells you to install a compat layer

https://github.com/jupyter/nbclassic

**Comment by LuckyJosh** [comment]
Though, staying at 6.x should be fine fore this year.

**Comment by maxnoe** [comment]
We should try using 7, will have a look later today

**Comment by maxnoe** [comment]
I think we actually don't need the extensions anymore. If I remember correctly, we needed this for the `--embed-images` options to the html converter, which now seems to be builtin into `nbconvert`.

**Comment by maxnoe** [comment]
Ok, this should be ready now and fix the CI and a couple of related issues / warnings I saw in the CI log.

All ohter PRs should rebase / merge main after this to get their CIs fixed.

Please review / merge @aknierim @chrbeckm

**Review by aknierim — APPROVED** [review]

**Pull request merged**
