### PR TITLE
Nbqa

### PR DESCRIPTION
**Pull request by chrbeckm**
Addresses #333

### CODE REVIEW

**Review by jpherdi — CHANGES_REQUESTED** [review]
Didn't we decide to go to 3.11 already?
What tools of nbqa did you use?

**Comment by chrbeckm** [comment]
I just used black. Python version is changed in a different pr.

**Review by jpherdi — APPROVED** [review]
One could also use pyupgrade but fine for now

**Comment by chrbeckm** [comment]
> One could also use pyupgrade but fine for now

Let's do that for each notebook separate, as sometimes we want a specific formatting. I noted that with black as well, e.g., in the matrix operations in numpy.

**Pull request merged**
