### PR TITLE
Wget tex fix

### PR DESCRIPTION
**Pull request by chrbeckm**
the `wget` for pictures of knuth and lamport didn't work for me

- added both pictures to `common/logos`
- latex slides: changed paths
- intro slides: changed paths
- `header.tex` 2019 → 2020

### CODE REVIEW

**Comment by MaxNoe** [comment]
I had the same problem and found a solution that still supports downloading: you need to set a user agent:

```
 wget -U 'Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0' ...
```

but maybe adding the files to the repo is just easier

**Comment by chrbeckm** [comment]
adding the files is easier, your solution doesn't work for me neither on Ubuntu or Windows

**Comment by MaxNoe** [comment]
This is what I use and it works fine:

```
       wget -U 'Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0' \
               http://amturing.acm.org/images/Lamport_2.jpg \
               -O $@ \
               --no-use-server-timestamps
```

**Comment by chrbeckm** [comment]
Thats the case for me too, it works for ´lamport´, not for ´knuth´.
I think saving the all files in the ´common´-folder is the best way.

**Review by MaxNoe — APPROVED** [review]

**Pull request merged**
