### PR TITLE
add long table-headers

### PR DESCRIPTION
**Pull request by hmoldenhauer**

### CODE REVIEW

**Comment by MaxNoe** [comment]
I am not entirely sure we should include this in the slides, it seems to be a rather special case and might distract from the actual content on this slide. Maybe better for a blog entry or troubleshooting?

**Comment by chrbeckm** [comment]
We could go for a blog, troubleshooting entry, referencing this pull request.

**Comment by Fresoquark** [comment]
Agreed. It seems a little bit distracting on that slide since its rather niche use.

**Comment by LuckyJosh** [comment]
Stale for over a year

**Pull request closed without merging**
