### PR TITLE
Rewrite tables exercises in favor of tabularray

### PR DESCRIPTION
**Pull request by aknierim**
The exercises now aim to teach the basic usage of tabularray.

* Added `tabularray` to header, added `tblr` libraries `siunitx` and `booktabs`
* Removed `booktabs` from header
* Changed tabular environments to `tblr`, added respective options in `tblr` header
* Due to the length of the data a few lines were deleted to let the tables be displayed nicely (I don't see the need to introduce `longtblr` yet)

Regarding the last point: While [tabularray](http://mirrors.ctan.org/macros/latex/contrib/tabularray/tabularray.pdf) certainly makes nicer tables, the spacing between rows can be too large for larger amounts of data. The spacing can of course be set with an option `rowsep` or `rowsep+` in the `tblr` environments header, but that would probably to much for this tutorial. Alternatively, the `longtblr` env could be used, but this again would go too deep, imo.

### CODE REVIEW

**Comment by LuckyJosh** [comment]
Maybe we could add the longtblr options to a short " advanced" section
 like the one for math typsetting.

**Comment by chrbeckm** [comment]
And/Or we build an additional exercise with a bit more explanation.
I would like to keep the slides as a complete overview, and not to hide something exclusively in the exercises.

**Comment by LuckyJosh** [comment]
Yes,  I meant a 2 slide section in the latex slides

**Comment by aknierim** [comment]
> Maybe we could add the longtblr options to a short " advanced" section like the one for math typsetting.

Yeah, I thought about that, too. Maybe right after the "Fortgeschritten: Mathe: Expert" section?

**Review by chrbeckm — APPROVED** [review]

**Pull request merged**
