### PR TITLE
Restructure, add toc, remove some stuff

### PR DESCRIPTION
**Pull request by MaxNoe**
* Added a ToC
* Removed format in favor of `f-string`
* Moved some stuff around to be more consistent

@LuckyJosh please check locally

### CODE REVIEW

**Comment by chrbeckm** [comment]
some cells are executed, some not
which way should it be in the repo?

**Comment by MaxNoe** [comment]
Ah damn. Thought I cleared everything.

**Comment by LuckyJosh** [comment]
Going to look into it further tomorrow, but I found this rather strange error.
The doubled cruly braces `{{` or `}}` seem to break something. :thinking: 

syntax-error-markdown

**Comment by LuckyJosh** [comment]
> Going to look into it further tomorrow, but I found this rather strange error.
> The doubled cruly braces `{{` or `}}` seem to break something. thinking
> 
> syntax-error-markdown

Nope, found the culprit ... some rouge extension was messing with the output :see_no_evil:

**Comment by LuckyJosh** [comment]
Looks good to me, just added some floats back in to replace the complex numbers before showing  the use of the multiple comparison operators `a < b < c`.

**Pull request merged**
