### PR TITLE
Fixed notebook warnings/errors

### PR DESCRIPTION
**Pull request by drgh0st**
Fixed errors that comes from imigration of python 3.5 to 3.6

### CODE REVIEW

**Comment by LuckyJosh** [comment]
Was there a problem with the format string in the sigmoid example `label=f"f(x; 1, {b}, 0)")`?

**Comment by LuckyJosh** [comment]
Ok sorry, my question was to unspecific. What is wrong with the f-string syntax? It looks fine on my end. :thinking:

**Comment by drgh0st** [comment]
it throw a syntax error at the end of both lines, but it don't say anything specific

**Comment by LuckyJosh** [comment]
Can you paste the error message (or a screenshot) here?
Are you sure that you are using Python 3.6?

**Comment by MaxNoe** [comment]
The old version worked with 3.6

**Comment by MaxNoe** [comment]
But the first fix is importan! The one with the undefined x.

**Comment by drgh0st** [comment]
i will open a new request tomorrow ;)

**Comment by MaxNoe** [comment]
Thanks

**Pull request closed without merging**
