### PR TITLE
fixes to the python notebook (maybe WIP)

### PR DESCRIPTION
**Pull request by LuckyJosh**
For now I only changed the references to the python version from 3.6 to 3.7.

I have thought about trimming (or shedding :smirk: ) the notebook, but I really cant find
anything to remove. Though I admit that I am very biased since I put most of it in there in
the first place. :see_no_evil: 

For instance, I thought of removing the formatting with `"{...}".format(...)` but you cant use f-strings to create latex expressions like the `siunitx`-example, since you cant use `\` in a f-string.
I find this to be a good example for the utility you can get out of a programming language.

To keep the time spent for this notebook at bay, I will do my best to stick to the material in the
notebook and not to answer as many "Can you also do ...?"-Questions with examples.

If you have any suggestions what to remove let me know.

### CODE REVIEW

**Comment by MaxNoe** [comment]
> but you cant use f-strings to create latex expressions like the siunitx-example, since you cant use \ in a f-string.

I don't understand. 

This works perfectly fine:
```python
a = 5
rf'\SI{{{a}}}{{\meter}}'
```

What do you mean?

**Comment by chrbeckm** [comment]
The part you could shorten is in my opinion the `format` part.
either you present `f-strings` or the `format`-part
both are, in my opinion too much and repetitive

**Comment by chrbeckm** [comment]
Is the extensive use of "man" wished?
I find it quite strange to read through.

**Comment by chrbeckm** [comment]
on my train journey tomorrow i will se how many _mans_ i can cancel

**Comment by LuckyJosh** [comment]
I resolved the conflicts in `python.ipynb` between `master` manually, should be ready to merge now.

**Pull request merged**
